[package]
name = "delta_encoding"
version.workspace = true
edition.workspace = true

[features]
default = []
std = []
test = ["dep:proptest", "dep:criterion"]

[dependencies]
criterion = { version = "0.8", optional = true }
proptest = { version = "1.11", optional = true }

[[bench]]
name = "encoding_bench"
harness = false
required-features = ["test", "std"]
